In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl

ROOT_DIR = Path.cwd().parent
DATA_DIR = ROOT_DIR.joinpath("data")

### 1. Pandas version


In [2]:
print(f"Pandas version: {pd.__version__}")
print(f"Polars version: {pl.__version__}")

Pandas version: 2.2.2
Polars version: 1.7.1


### Getting the data


In [3]:
csv_uri = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"
pq_path = DATA_DIR.joinpath("laptops.pq")

if pq_path.exists():
    df = pl.read_parquet(pq_path)
else:
    df = pl.read_csv(csv_uri)
    df.write_parquet(pq_path)


### 2. Records count


In [4]:
print(f"shape: {df.shape}")
print(f"num of records: {df.shape[0]}")
print(f"num of columns: {df.shape[1]}")

shape: (2160, 12)
num of records: 2160
num of columns: 12


In [5]:
df.schema

Schema([('Laptop', String),
        ('Status', String),
        ('Brand', String),
        ('Model', String),
        ('CPU', String),
        ('RAM', Int64),
        ('Storage', Int64),
        ('Storage type', String),
        ('GPU', String),
        ('Screen', Float64),
        ('Touch', String),
        ('Final Price', Float64)])

In [6]:
df.glimpse()

Rows: 2160
Columns: 12
$ Laptop       <str> 'ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core i5-1235U/8GB/512GB SSD/15.6"', 'Alurin Go Start Intel Celeron N4020/8GB/256GB SSD/15.6"', 'ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core i3-1215U/8GB/256GB SSD/15.6"', 'MSI Katana GF66 12UC-082XES Intel Core i7-12700H/16GB/1TB SSD/RTX3050/15.6"', 'HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB SSD/15.6"', 'MSI Crosshair 17 C12VF-264XES Intel Core i7-12650H/32GB/1TB SSD/RTX 4060/17.3"', 'Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8GB/256GB SSD/14"', 'ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-1065G7/8GB/512GB SSD/15.6"', 'Medion Akoya E15415 Intel Core i5-10210U/8GB/256GB SSD/15.6"', 'HP Victus 16-d1038ns Intel Core i7-12700H/16GB/512GB SSD/RTX 3050/16.1"'
$ Status       <str> 'New', 'New', 'New', 'New', 'New', 'New', 'New', 'New', 'New', 'New'
$ Brand        <str> 'Asus', 'Alurin', 'Asus', 'MSI', 'HP', 'MSI', 'Lenovo', 'Asus', 'Medion', 'HP'
$ Model        <str> 'ExpertBook', 'Go', 'ExpertB

In [7]:
df.head()

shape: (5, 12)
┌─────────────────────┬────────┬────────┬────────────┬───┬──────────┬────────┬───────┬─────────────┐
│ Laptop              ┆ Status ┆ Brand  ┆ Model      ┆ … ┆ GPU      ┆ Screen ┆ Touch ┆ Final Price │
│ ---                 ┆ ---    ┆ ---    ┆ ---        ┆   ┆ ---      ┆ ---    ┆ ---   ┆ ---         │
│ str                 ┆ str    ┆ str    ┆ str        ┆   ┆ str      ┆ f64    ┆ str   ┆ f64         │
╞═════════════════════╪════════╪════════╪════════════╪═══╪══════════╪════════╪═══════╪═════════════╡
│ ASUS ExpertBook B1  ┆ New    ┆ Asus   ┆ ExpertBook ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 1009.0      │
│ B1502CBA-EJ…        ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ Alurin Go Start     ┆ New    ┆ Alurin ┆ Go         ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 299.0       │
│ Intel Celeron …     ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ ASUS ExpertBook B1  ┆ New    ┆ Asus   ┆ ExpertBook ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 789.0       │
│ B1502CBA-EJ…        ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ MSI Katana GF66     ┆ New    ┆ MSI    ┆ Katana     ┆ … ┆ RTX 3050 ┆ 15.6   ┆ No    ┆ 1199.0      │
│ 12UC-082XES In…     ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ HP 15S-FQ5085NS     ┆ New    ┆ HP     ┆ 15S        ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 669.01      │
│ Intel Core i5-…     ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
└─────────────────────┴────────┴────────┴────────────┴───┴──────────┴────────┴───────┴─────────────┘

In [8]:
df.describe()

shape: (9, 13)
┌────────────┬─────────────────┬─────────────┬───────┬───┬───────┬───────────┬───────┬─────────────┐
│ statistic  ┆ Laptop          ┆ Status      ┆ Brand ┆ … ┆ GPU   ┆ Screen    ┆ Touch ┆ Final Price │
│ ---        ┆ ---             ┆ ---         ┆ ---   ┆   ┆ ---   ┆ ---       ┆ ---   ┆ ---         │
│ str        ┆ str             ┆ str         ┆ str   ┆   ┆ str   ┆ f64       ┆ str   ┆ f64         │
╞════════════╪═════════════════╪═════════════╪═══════╪═══╪═══════╪═══════════╪═══════╪═════════════╡
│ count      ┆ 2160            ┆ 2160        ┆ 2160  ┆ … ┆ 789   ┆ 2156.0    ┆ 2160  ┆ 2160.0      │
│ null_count ┆ 0               ┆ 0           ┆ 0     ┆ … ┆ 1371  ┆ 4.0       ┆ 0     ┆ 0.0         │
│ mean       ┆ null            ┆ null        ┆ null  ┆ … ┆ null  ┆ 15.168112 ┆ null  ┆ 1312.638509 │
│ std        ┆ null            ┆ null        ┆ null  ┆ … ┆ null  ┆ 1.203329  ┆ null  ┆ 911.475417  │
│ min        ┆ ASUS  ROG       ┆ New         ┆ Acer  ┆ … ┆ 610 M ┆ 10.1      ┆ No    ┆ 201.05      │
│            ┆ Zephyrus M16    ┆             ┆       ┆   ┆       ┆           ┆       ┆             │
│            ┆ GU604VI…        ┆             ┆       ┆   ┆       ┆           ┆       ┆             │
│ 25%        ┆ null            ┆ null        ┆ null  ┆ … ┆ null  ┆ 14.0      ┆ null  ┆ 661.11      │
│ 50%        ┆ null            ┆ null        ┆ null  ┆ … ┆ null  ┆ 15.6      ┆ null  ┆ 1032.0      │
│ 75%        ┆ null            ┆ null        ┆ null  ┆ … ┆ null  ┆ 15.6      ┆ null  ┆ 1708.96     │
│ max        ┆ Vant Moove3-14  ┆ Refurbished ┆ Vant  ┆ … ┆ T 600 ┆ 18.0      ┆ Yes   ┆ 7150.47     │
│            ┆ Intel Core      ┆             ┆       ┆   ┆       ┆           ┆       ┆             │
│            ┆ i5-1…           ┆             ┆       ┆   ┆       ┆           ┆       ┆             │
└────────────┴─────────────────┴─────────────┴───────┴───┴───────┴───────────┴───────┴─────────────┘

### 3. Laptop brands


In [9]:
df.get_column("Brand").n_unique()

27

### 4. Missing values


In [10]:
df.select(pl.all().has_nulls()).sum().sum_horizontal()[0]

3

In [11]:
df.null_count().transpose(include_header=True, column_names=["null_count"]).filter(
    pl.col("null_count") != 0
).sort(pl.col("null_count"), descending=True)

shape: (3, 2)
┌──────────────┬────────────┐
│ column       ┆ null_count │
│ ---          ┆ ---        │
│ str          ┆ u32        │
╞══════════════╪════════════╡
│ GPU          ┆ 1371       │
│ Storage type ┆ 42         │
│ Screen       ┆ 4          │
└──────────────┴────────────┘

### 5. Maximum final price


In [12]:
df.filter(pl.col("Brand") == "Dell").get_column("Final Price").max()

3936.0

### 6. Median value of Screen


1. Find the median value of Screen column in the dataset.
1. Next, calculate the most frequent value of the same Screen column.
1. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
1. Now, calculate the median value of Screen once again.


In [13]:
screen = df.get_column("Screen")
median = screen.median()
mode = screen.mode()[0]
new_median = screen.fill_null(mode).median()

In [14]:
print(f"median: {median}")
print(f"mode: {mode}")
print(f"median after imputation: {new_median}")

if median == new_median:
    print("The median value didn't change")
else:
    print("The median value changed")

median: 15.6
mode: 15.6
median after imputation: 15.6
The median value didn't change


### 7. Sum of weights


1. Select all the "Innjoo" laptops from the dataset.
1. Select only columns RAM, Storage, Screen.
1. Get the underlying NumPy array. Let's call it X.
1. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
1. Compute the inverse of XTX.
1. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
1. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
1. What's the sum of all the elements of the result?


In [39]:
%%timeit
X = (
    df.filter(pl.col("Brand") == "Innjoo")
    .select(pl.col("RAM", "Storage", "Screen"))
    .to_numpy()
)
print(X)

263 μs ± 21.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [17]:
XTX = X.T @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [18]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [19]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [20]:
w = XTX_inv @ X.T @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [21]:
print(f"Sum of weights: {w.sum()}")

Sum of weights: 91.2998806299555


### Others


In [31]:
df.head()

shape: (5, 12)
┌─────────────────────┬────────┬────────┬────────────┬───┬──────────┬────────┬───────┬─────────────┐
│ Laptop              ┆ Status ┆ Brand  ┆ Model      ┆ … ┆ GPU      ┆ Screen ┆ Touch ┆ Final Price │
│ ---                 ┆ ---    ┆ ---    ┆ ---        ┆   ┆ ---      ┆ ---    ┆ ---   ┆ ---         │
│ str                 ┆ str    ┆ str    ┆ str        ┆   ┆ str      ┆ f64    ┆ str   ┆ f64         │
╞═════════════════════╪════════╪════════╪════════════╪═══╪══════════╪════════╪═══════╪═════════════╡
│ ASUS ExpertBook B1  ┆ New    ┆ Asus   ┆ ExpertBook ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 1009.0      │
│ B1502CBA-EJ…        ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ Alurin Go Start     ┆ New    ┆ Alurin ┆ Go         ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 299.0       │
│ Intel Celeron …     ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ ASUS ExpertBook B1  ┆ New    ┆ Asus   ┆ ExpertBook ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 789.0       │
│ B1502CBA-EJ…        ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ MSI Katana GF66     ┆ New    ┆ MSI    ┆ Katana     ┆ … ┆ RTX 3050 ┆ 15.6   ┆ No    ┆ 1199.0      │
│ 12UC-082XES In…     ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
│ HP 15S-FQ5085NS     ┆ New    ┆ HP     ┆ 15S        ┆ … ┆ null     ┆ 15.6   ┆ No    ┆ 669.01      │
│ Intel Core i5-…     ┆        ┆        ┆            ┆   ┆          ┆        ┆       ┆             │
└─────────────────────┴────────┴────────┴────────────┴───┴──────────┴────────┴───────┴─────────────┘

In [49]:
df.select(pl.col("CPU", "RAM", "Storage")).filter(pl.col("CPU").str.contains("Celeron"))

shape: (94, 3)
┌───────────────┬─────┬─────────┐
│ CPU           ┆ RAM ┆ Storage │
│ ---           ┆ --- ┆ ---     │
│ str           ┆ i64 ┆ i64     │
╞═══════════════╪═════╪═════════╡
│ Intel Celeron ┆ 8   ┆ 256     │
│ Intel Celeron ┆ 8   ┆ 256     │
│ Intel Celeron ┆ 8   ┆ 256     │
│ Intel Celeron ┆ 8   ┆ 64      │
│ Intel Celeron ┆ 8   ┆ 256     │
│ …             ┆ …   ┆ …       │
│ Intel Celeron ┆ 8   ┆ 128     │
│ Intel Celeron ┆ 8   ┆ 64      │
│ Intel Celeron ┆ 4   ┆ 128     │
│ Intel Celeron ┆ 8   ┆ 256     │
│ Intel Celeron ┆ 4   ┆ 64      │
└───────────────┴─────┴─────────┘

In [48]:
df.group_by(pl.col("Brand")).agg(
    pl.len(),
    pl.col("Final Price").max().alias("Max Final Price"),
    pl.col("Final Price").min().alias("Min Final Price"),
    pl.col("Final Price").mean().alias("Mean Final Price"),
)

shape: (27, 5)
┌───────────┬─────┬─────────────────┬─────────────────┬──────────────────┐
│ Brand     ┆ len ┆ Max Final Price ┆ Min Final Price ┆ Mean Final Price │
│ ---       ┆ --- ┆ ---             ┆ ---             ┆ ---              │
│ str       ┆ u32 ┆ f64             ┆ f64             ┆ f64              │
╞═══════════╪═════╪═════════════════╪═════════════════╪══════════════════╡
│ Microsoft ┆ 77  ┆ 3747.91         ┆ 599.01          ┆ 1595.543247      │
│ Acer      ┆ 137 ┆ 3691.0          ┆ 264.14          ┆ 1001.285766      │
│ Lenovo    ┆ 366 ┆ 5018.14         ┆ 239.0           ┆ 1087.72388       │
│ Millenium ┆ 2   ┆ 2312.71         ┆ 1640.98         ┆ 1976.845         │
│ Razer     ┆ 37  ┆ 4999.01         ┆ 1232.74         ┆ 3265.701622      │
│ …         ┆ …   ┆ …               ┆ …               ┆ …                │
│ Apple     ┆ 116 ┆ 3849.0          ┆ 299.0           ┆ 1578.227672      │
│ Denver    ┆ 1   ┆ 329.95          ┆ 329.95          ┆ 329.95           │
│ Asus      ┆ 415 ┆ 5758.14         ┆ 239.25          ┆ 1269.380699      │
│ Jetwing   ┆ 1   ┆ 469.27          ┆ 469.27          ┆ 469.27           │
│ Vant      ┆ 11  ┆ 1217.01         ┆ 632.0           ┆ 1047.455455      │
└───────────┴─────┴─────────────────┴─────────────────┴──────────────────┘

In [78]:
df.select(
    pl.col("Brand"),
    pl.when(pl.col("RAM") > 8)
    .then(pl.lit("Sufficient"))
    .otherwise(pl.lit("Upgrade"))
    .alias("Recommendation"),
)

shape: (2_160, 2)
┌────────┬────────────────┐
│ Brand  ┆ Recommendation │
│ ---    ┆ ---            │
│ str    ┆ str            │
╞════════╪════════════════╡
│ Asus   ┆ Upgrade        │
│ Alurin ┆ Upgrade        │
│ Asus   ┆ Upgrade        │
│ MSI    ┆ Sufficient     │
│ HP     ┆ Sufficient     │
│ …      ┆ …              │
│ Razer  ┆ Sufficient     │
│ Razer  ┆ Sufficient     │
│ Razer  ┆ Sufficient     │
│ Razer  ┆ Sufficient     │
│ Razer  ┆ Sufficient     │
└────────┴────────────────┘

In [82]:
df.select(
    pl.col("Brand"),
    pl.col("RAM"),
    pl.when(pl.col("RAM") < 8)
    .then(pl.lit("Upgrade"))
    .otherwise(
        pl.when(pl.col("RAM") > 16)
        .then(pl.lit("Overkill"))
        .otherwise(pl.lit("Sufficient"))
    )
    .alias("Recommendation"),
)

shape: (2_160, 3)
┌────────┬─────┬────────────────┐
│ Brand  ┆ RAM ┆ Recommendation │
│ ---    ┆ --- ┆ ---            │
│ str    ┆ i64 ┆ str            │
╞════════╪═════╪════════════════╡
│ Asus   ┆ 8   ┆ Sufficient     │
│ Alurin ┆ 8   ┆ Sufficient     │
│ Asus   ┆ 8   ┆ Sufficient     │
│ MSI    ┆ 16  ┆ Sufficient     │
│ HP     ┆ 16  ┆ Sufficient     │
│ …      ┆ …   ┆ …              │
│ Razer  ┆ 16  ┆ Sufficient     │
│ Razer  ┆ 16  ┆ Sufficient     │
│ Razer  ┆ 32  ┆ Overkill       │
│ Razer  ┆ 16  ┆ Sufficient     │
│ Razer  ┆ 16  ┆ Sufficient     │
└────────┴─────┴────────────────┘